# 
# * Builds from the Dockerfile in the current directory.
# * Forwards the exposed port 5000 on the container to 
#   port 5000 on the host machine..
# * Mounts the current directory on the host to /code inside 
#   the container allowing you to modify the code without 
#   having to rebuild the image.
version: '2'

services:

  pl-fhir:
    container_name: pl-fhir
    build: ./pl-fhir
    restart: always
    ports:
    - "8080:8080"

  pl-mysql:
    container_name: pl-mysql
    build: ./pl-mysql
    restart: always
    ports:
     - "3306:3306"

  pl-fhircxn:
    container_name: pl-fhircxn
    build: ./pl-fhircxn
    restart: always
    links:
    - pl-mysql
    - pl-fhir

  pl-webui:
    container_name: pl-webui
    build: ./pl-webui
    restart: always
    ports:
     - "5000:5000"
    links:
     - pl-mysql




